# Generated by Django 6.0.8 on 2026-08-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='currency',
            field=models.CharField(choices=[('USD', '$ USD - US Dollar'), ('EUR', '€ EUR - Euro'), ('TRY', '₺ TRY - Turkish Lira'), ('GBP', '£ GBP - British Pound'), ('JPY', '¥ JPY - Japanese Yen'), ('CAD', 'C$ CAD - Canadian Dollar'), ('AUD', 'A$ AUD - Australian Dollar')], default='USD', max_length=3),
        ),
    ]
