# Generated by Django 5.2.17 on 2026-08-14 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventbooking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventbooking',
            options={'ordering': ['-booked_at'], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
    ]
