# Generated by Django 6.0.7 on 2026-08-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_widen_category_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.AddField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(blank=True, db_table='event_category', related_name='events', to='events.category'),
        ),
    ]
