# Generated by Django 6.0.7 on 2026-08-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='publish_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='approved', max_length=20),
        ),
    ]
