# Generated by Django 6.0.7 on 2026-08-25 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_migrate_event_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.RemoveField(
            model_name='event',
            name='custom_category',
        ),
    ]
