# Generated by Django 6.0.7 on 2026-08-27 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_publish_status'),
        ('events', '0011_remove_event_category_remove_event_custom_category'),
    ]

    operations = [
    ]
