# Generated by Django 6.0.7 on 2026-08-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_merge_20260827_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking', 'Booking'), ('cancellation', 'Cancellation'), ('event_approval', 'Event Approval'), ('event_denial', 'Event Denial'), ('event_request', 'Event Request'), ('organizer_approval', 'Organizer Approval'), ('organizer_denial', 'Organizer Denial'), ('organizer_request', 'Organizer Request'), ('system', 'System')], db_index=True, default='system', max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='publish_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20),
        ),
    ]
