# Generated by Django 6.0.7

from django.db import migrations, models


def mark_existing_admins_verified(apps, schema_editor):
    User = apps.get_model('authentication', 'User')
    User.objects.filter(role='admin').update(email_verified=True)
    User.objects.filter(is_superuser=True).update(email_verified=True)


def unmark_existing_admins_verified(apps, schema_editor):
    User = apps.get_model('authentication', 'User')
    User.objects.filter(role='admin').update(email_verified=False)
    User.objects.filter(is_superuser=True).update(email_verified=False)


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            mark_existing_admins_verified,
            unmark_existing_admins_verified,
        ),
    ]
