# Generated by Django 6.0.7 on 2026-08-25 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_add_user_email_verified'),
        ('authentication', '0006_user_organizer_status'),
    ]

    operations = [
    ]
